Feat: Implement Core Marshal
SprocketBot/bot-service pull request #1
Opened 2021-06-22 05:02 UTC by 0c370t

Marshal is our homebrew discord framework we will be using, this implements the core, with support for `@Command` and `@CommandNotFound`

2021-06-23 02:33 UTC, 0c370t commented on src/marshal/marshal.ts
> +    private registerAllCommands(@Inject(CommandManagerService) cms: CommandManagerService): void {
Remove @Inject decorator

2021-06-26 21:49 UTC, zachstence requested changes

2021-06-26 21:49 UTC, zachstence commented on src/marshal/marshal.ts
> +    private registerAllCommands(cms: CommandManagerService): void {
Why is `cms` passed into this function rather than just using the property `cms__`?

2021-06-26 21:49 UTC, zachstence commented on src/marshal/marshal.ts
> +            this.logger___.error(parseResult);
Should we be quietly failing and returning here, or should we throw an exception to break whatever execution path we're in?

2021-06-26 21:49 UTC, zachstence commented on src/marshal/decorators/command.decorator.ts
> +    const commandMetadata: CommandMetadata = {
Do we have support for commands with arguments?

2021-06-26 21:49 UTC, zachstence commented on src/marshal/command-manager/command-manager.service.ts
> +    extractCommandKey(message: string): string | undefined {
Should we have any logging in here when commands are/are not found?

2021-06-26 21:49 UTC, zachstence commented on src/marshal/command-manager/command-manager.service.ts
> +            if (this.commands.has(alias)) {
Should this be using `.toLowerCase()` to check if the alias already exists?

2021-06-26 21:49 UTC, zachstence commented on src/marshal/command-manager/command-manager.service.ts
> +            this.logger.debug(`Registering command ${alias}`);
Log/error the alias in lowercase since they are case insensitive

2021-06-26 21:49 UTC, zachstence commented on src/marshal/command-manager/command-manager.service.spec.ts
> +        }).toThrow();
Add the expected error inside `.toThrow(...)`

2021-06-26 21:49 UTC, zachstence commented on src/marshal/command-manager/command-manager.service.spec.ts
> +        expect(service.commands.size).toBe(2);
Its important not only that a command is registered, but that it is registered with the correct info. You should `expect` that `service.commands.get("ping")` and `service.commands.get("pong")` are defined with the correct information

2021-06-26 21:49 UTC, zachstence commented on src/marshal/command-manager/command-manager.service.spec.ts
> +        expect(service.commands.size).toBe(1);
Its important not only that a command is registered, but that it is registered with the correct info. You should `expect` that `service.commands.get("ping")` isdefined with the correct information

2021-06-26 21:49 UTC, zachstence commented on src/marshal/command-manager/command-manager.service.spec.ts
> +    });
Empty `beforeAll`

2021-06-26 21:49 UTC, zachstence commented on src/marshal/command-manager/command-manager.service.spec.ts
> +            commandAliases: ["ping"],
I want to revisit the idea of using random strings/numbers/etc where possible in tests, this would be a good spot. We can always retroactively update tests to use randomness but just wanted to put this note here to remind us about it

2021-06-26 21:49 UTC, zachstence commented on src/marshal/marshal.ts
> +            this.logger___.error(parseResult);
Also, this block is missed by unit tests.

2021-06-26 21:49 UTC, zachstence commented on src/marshal/marshal.ts
> +            return;
This block is missed by unit tests.

2021-06-26 21:49 UTC, zachstence commented on src/marshal/decorators/command.decorator.ts
> +        return result;
This is missed by unit tests

2021-06-26 21:49 UTC, zachstence commented on src/marshal/decorators/command-not-found.decorator.ts
> +        return result;
This is missed by unit tests

2021-06-27 18:49 UTC, 0c370t commented on src/marshal/decorators/command.decorator.ts
> +        functionName: key.toString(),
No, because they are scoped to a class and you cannot have 2 functions of the same name in one class

2021-06-27 18:50 UTC, 0c370t commented on config/test.json
> +        "prefix": "awsdfasfasfasdfasdf"
Just a test var

2021-06-27 18:52 UTC, 0c370t commented on src/marshal/marshal.ts
> +            this.logger___.error(parseResult);
This block exists for type safety, and should not be possible

2021-06-27 18:53 UTC, 0c370t commented on src/marshal/marshal.ts
> +            return;
See above

2021-06-27 18:53 UTC, 0c370t commented on src/marshal/command-manager/command-manager.service.ts
> +    extractCommandKey(message: string): string | undefined {
No, that would log every message that the bot could see

2021-06-27 18:53 UTC, 0c370t commented on src/marshal/command-manager/command-manager.service.ts
> +            this.logger.debug(`Registering command ${alias}`);
Case sensitive Ctrl+F will still see the formatting provided in the string, best to represent it that way instead of sending back a changed version

2021-06-27 18:54 UTC, 0c370t commented on src/marshal/decorators/command.decorator.ts
> +        return result;
Kinda, unit tests and coverage had a hard time with the reflection stuff going on here, we can talk about it this afternoon if you want, but we can't get coverage in this function

2021-06-27 18:55 UTC, 0c370t commented on src/marshal/decorators/command.decorator.ts
> +    const commandMetadata: CommandMetadata = {
Not as part of the framework, argument parsing needs to be done manually (for now)

2021-06-27 18:56 UTC, 0c370t commented on src/marshal/marshal.ts
> +    private readonly logger___ = new Logger(Marshal.name);
Will `_logger` conflict with child classes if they also try to have one? If it will, then this will remain as is

2021-06-29 03:51 UTC, 0c370t commented on src/marshal/decorators/command-not-found.decorator.ts
> +        return result;
Kinda, unit tests and coverage had a hard time with the reflection stuff going on here, we can talk about it this afternoon if you want, but we can't get coverage in this function

2021-06-29 03:51 UTC, 0c370t commented on src/marshal/marshal.ts
> +    private registerAllCommands(cms: CommandManagerService): void {
cms is no longer a property

2021-06-29 03:52 UTC, 0c370t commented on src/marshal/command-manager/command-manager.service.spec.ts
> +        expect(service.commands.size).toBe(2);
The information is not saved, it is only a function reference; which we can't test for because jest request that we do some prototype stuff in order to spy on replaced methods

2021-06-29 23:48 UTC, ben4643 commented
👍

2021-06-30 01:22 UTC, zachstence commented on src/marshal/marshal.ts
> +    private readonly logger___ = new Logger(Marshal.name);
True. Maybe we could rename it to something like `__logger__` to emphasize its private and shouldn't be used outside this class

2021-06-30 23:16 UTC, 0c370t commented
@zachstence can this be merged?

2021-06-30 23:18 UTC, merged