GraphQL
SprocketBot/bot-service pull request #13
Opened 2021-12-28 16:09 UTC by zachstence

2022-01-02 02:01 UTC, 0c370t requested changes

2022-01-02 02:10 UTC, zachstence commented on src/marshal/types.ts
> +        id: string;
Yeah, just did enough for now. We should address in the future

2022-01-02 02:10 UTC, zachstence commented on src/marshal/marshal.ts
> +        protected readonly embedService: EmbedService,
Will remove and have each Command Marshal inject it themselves if they need it

2022-01-02 02:10 UTC, zachstence commented on src/marshal/decorators/command.decorator.ts
> +            if (!user) throw new Error(`getUserByAuthAccount returned ${JSON.stringify(res)}`);
Possibly, I'll make it more generic

2022-01-02 02:10 UTC, zachstence commented on src/administrator-commands/sprocket-configuration.marshal.ts
> +    // TODO do we support optional arguments? These could be the same command with key being optional
👀

2022-01-03 00:30 UTC, zachstence commented on src/administrator-commands/sprocket-configuration.marshal.ts
> +import {table} from "src/util/table";
68f6e26

2022-01-03 00:30 UTC, zachstence commented on src/administrator-commands/sprocket-configuration.marshal.ts
> +    // TODO do we support optional arguments? These could be the same command with key being optional
94206df

2022-01-03 00:30 UTC, zachstence commented on src/marshal/decorators/command.decorator.ts
> +            if (!user) throw new Error(`getUserByAuthAccount returned ${JSON.stringify(res)}`);
619417e

2022-01-03 00:30 UTC, zachstence commented on src/marshal/marshal.ts
> +        protected readonly embedService: EmbedService,
c7be6ca

2022-01-03 00:32 UTC, 0c370t approved these changes

2022-01-03 00:32 UTC, merged