feat: add member to context
SprocketBot/bot-service pull request #5
Opened 2021-07-18 23:09 UTC by 0c370t

2021-07-19 12:11 UTC, zachstence requested changes

2021-07-19 12:11 UTC, zachstence commented on src/marshal/decorators/command.decorator.ts
> +            }
Just a semantic preference, but move the `if` error block before the `context.member` assignment

2021-07-19 12:11 UTC, zachstence commented on src/marshal/marshal.spec.ts
We need test(s) asserting that the context/member are correctly given to the CommandFunction

2021-07-19 12:11 UTC, zachstence commented on src/marshal/types.ts
> + * This type is temporary, and will be replaced when @sprocketbot/entities becomes available
Put a `TODO` here so we don't lose this

2021-07-19 12:11 UTC, zachstence commented on src/marshal/types.ts
> +    member?: TempMember;
Would `author` be a better name to indicate that this member on the context is the one who used the command?

2021-09-04 20:00 UTC, 0c370t commented on src/marshal/types.ts
> + * This type is temporary, and will be replaced when @sprocketbot/entities becomes available
@zachstence we probably still need to figure this out

2021-09-09 00:27 UTC, merged